spring:
  application:
    name: ambulance-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ambulance_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8085
  servlet:
    context-path: /ambulance-service

